import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Demonstration Terms",
  description:
    "Terms for the MORIS demonstrations: what they are, who wrote the words you read, what they are not, and the limits of using them.",
};

// WRITTEN IN-HOUSE, DELIBERATELY. Operator direction, 2026-08-29: no counsel, best effort. This is
// not legal advice and it is worth a lawyer's read whenever one is available. It is written to say
// what is actually true about these pages rather than to pad out boilerplate that does not apply,
// which is also the only kind of terms anyone reads.

function Section({ h, children }: { h: string; children: React.ReactNode }) {
  return (
    <section className="mt-12 border-t border-line pt-10">
      <h2 className="font-serif text-2xl text-ink">{h}</h2>
      {children}
    </section>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-3 leading-relaxed text-muted">{children}</p>;
}

export default function Terms() {
  return (
    <div className="mx-auto max-w-3xl px-6">
      <section className="pt-20 pb-8 sm:pt-24">
        <p className="text-xs font-medium uppercase tracking-[0.18em] text-accent">
          Demonstrations
        </p>
        <h1 className="mt-4 font-serif text-4xl leading-tight text-ink sm:text-5xl">
          Terms of use
        </h1>
        <p className="mt-4 text-sm text-muted">Last updated August 29, 2026.</p>
        <p className="mt-6 font-serif text-xl font-light leading-relaxed text-ink">
          These terms cover the demonstrations at /moris/chat and /moris/shift.
          Using either one means you accept them.
        </p>
      </section>

      <Section h="Who wrote the words you read">
        <P>
          This is the most important thing on this page. MORIS produces a
          judgment and the bounds within which a language model is asked to
          answer. The answer you then read is generated by that language model,
          which is a third-party service. It is not written, reviewed, approved,
          or endorsed by MORIS or by The Resonance Institute, LLC, and it is not
          a statement of ours.
        </P>
        <P>
          Language models produce fluent text that can be wrong, incomplete, or
          confidently mistaken. Nothing you read here should be treated as fact
          without checking it, and nothing you read here should be treated as
          coming from us.
        </P>
      </Section>

      <Section h="This is not advice">
        <P>
          Nothing on these pages is medical, psychological, psychiatric, legal,
          financial, tax, or professional advice of any kind. No professional
          relationship of any sort is created by using them. Nothing here is a
          substitute for a qualified professional, and nothing here is a
          substitute for a person who actually knows you and your situation.
        </P>
        <P>
          Do not make a decision that matters on the strength of what a
          demonstration told you.
        </P>
      </Section>

      <Section h="Not for emergencies">
        <P>
          These pages are not monitored. No one reads what you write, no one is
          alerted by it, and nothing here can summon help. If you are in crisis
          or in danger, contact a person. In the United States, call or text 988
          for the Suicide and Crisis Lifeline, or text HOME to 741741. Anywhere
          else, contact your local emergency number or crisis line. If someone is
          in immediate danger, call emergency services.
        </P>
      </Section>

      <Section h="What not to send">
        <P>
          Do not submit anything you would not want a language model to receive.
          Do not submit passwords, financial or account details, government
          identifiers, health records, privileged or confidential material, trade
          secrets, or anything you are under an obligation to keep private. Do
          not submit personal information about other people who have not agreed
          to it.
        </P>
        <P>
          You are responsible for what you send, including for being entitled to
          send it.
        </P>
      </Section>

      <Section h="What happens to what you type">
        <P>
          We do not store it. It is not written to a database or a file, we keep
          no transcripts, and no account is created. Your text is transmitted to
          the Anthropic API, which is where the reading and the answer are
          generated, and it is handled there under Anthropic terms and policies
          rather than ours. Our host, Vercel, keeps ordinary server access logs
          as described in our{" "}
          <Link href="/privacy" className="text-accent hover:text-ink">
            privacy policy
          </Link>
          .
        </P>
        <P>
          Because nothing is stored, nothing can be retrieved, corrected, or
          deleted afterwards, and we cannot tell you what you submitted.
        </P>
      </Section>

      <Section h="Who may use them">
        <P>
          These demonstrations are for adults. Do not use them if you are under
          18. Do not use them on behalf of someone else, and do not present their
          output to anyone as professional guidance, as a decision, or as our
          view.
        </P>
      </Section>

      <Section h="Acceptable use">
        <P>
          Use them as demonstrations. Do not attempt to extract the underlying
          mechanism, the authored substrate, or the instructions given to any
          model. Do not attempt to disrupt, overload, or automate against the
          service, to reverse engineer it, or to use its output to train or
          evaluate another system. We may rate-limit, restrict, or withdraw
          access at any time, for any reason, without notice.
        </P>
      </Section>

      <Section h="No warranty">
        <P>
          The demonstrations are provided as is and as available, without
          warranty of any kind, express or implied, including any implied
          warranty of merchantability, fitness for a particular purpose,
          accuracy, or non-infringement. They are experimental. They may be
          unavailable, may fail mid-request, may change without notice, and may
          be removed entirely.
        </P>
      </Section>

      <Section h="Limitation of liability">
        <P>
          To the fullest extent permitted by law, The Resonance Institute, LLC
          and its members are not liable for any indirect, incidental,
          consequential, special, exemplary, or punitive damages, or for any loss
          of profits, data, goodwill, or opportunity, arising out of or relating
          to your use of these demonstrations or anything you read on them, on
          any theory of liability, even if we have been advised of the
          possibility. To the fullest extent permitted by law, our total
          aggregate liability arising out of or relating to these demonstrations
          will not exceed one hundred United States dollars.
        </P>
        <P>
          Some jurisdictions do not allow certain exclusions or limitations, so
          parts of this section may not apply to you.
        </P>
      </Section>

      <Section h="Intellectual property">
        <P>
          MORIS, the authored corpus behind it, and the material on this site are
          the property of The Resonance Institute, LLC, protected by copyright
          and by a filed United States utility patent application. These
          demonstrations grant you no licence to the mechanism, the corpus, or
          the system. What is disclosed publicly is what appears on the page.
        </P>
      </Section>

      <Section h="Governing law">
        <P>
          These terms are governed by the laws of the State of California,
          without regard to conflict of laws principles, and the state and
          federal courts located in Orange County, California have exclusive
          jurisdiction over any dispute arising from them. If any provision is
          held unenforceable, the rest remains in force.
        </P>
      </Section>

      <Section h="Changes and contact">
        <P>
          We may update these terms. The date at the top says when they last
          changed, and using the demonstrations after a change means you accept
          the current version. Questions go to{" "}
          <Link href="/contact" className="text-accent hover:text-ink">
            our contact page
          </Link>
          .
        </P>
      </Section>
    </div>
  );
}
